-- Backfill migration: brain.card_transactions_raw
-- Bang nay da duoc tao truoc do (khong qua apply_migration, co the qua execute_sql)
-- va dang duoc dung that trong production (email-transaction-sync Edge Function).
-- Migration nay CHI de ghi lai lich su cho dung, dung CREATE TABLE IF NOT EXISTS
-- + moi statement idempotent de an toan tuyet doi neu chay lai.
-- Cau truc lay dung 100% tu pg_catalog cua bang dang ton tai, khong doan.

CREATE TABLE IF NOT EXISTS brain.card_transactions_raw (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank text NOT NULL,
  card_last4 text,
  txn_datetime timestamptz,
  amount numeric NOT NULL,
  currency text DEFAULT 'VND',
  merchant_raw text,
  category text,
  email_message_id text,
  email_subject text,
  raw_snippet text,
  is_reviewed boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  payment_method text,
  direction text NOT NULL DEFAULT 'out' CHECK (direction IN ('in', 'out'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_card_txn_email_unique ON brain.card_transactions_raw (email_message_id);
CREATE INDEX IF NOT EXISTS idx_card_txn_datetime ON brain.card_transactions_raw (txn_datetime);
CREATE INDEX IF NOT EXISTS idx_card_txn_category ON brain.card_transactions_raw (category);

ALTER TABLE brain.card_transactions_raw ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policy WHERE polrelid = 'brain.card_transactions_raw'::regclass AND polname = 'service_role_all'
  ) THEN
    CREATE POLICY service_role_all ON brain.card_transactions_raw
      FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON brain.card_transactions_raw TO service_role;
